# Generated by Django 4.2 on 2023-04-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commit', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='author',
            new_name='writer',
        ),
        migrations.AddField(
            model_name='commit',
            name='title',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterModelTable(
            name='commit',
            table='my_commit',
        ),
    ]
