# Generated by Django 4.2 on 2023-04-16 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commit', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='like',
        ),
        migrations.AddField(
            model_name='commit',
            name='like_commit',
            field=models.ManyToManyField(related_name='like_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
