# Generated by Django 4.2 on 2023-04-16 21:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commit', '0003_remove_commit_like_commit_like_commit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='like_commit',
            field=models.ManyToManyField(related_name='like_commit', to=settings.AUTH_USER_MODEL),
        ),
    ]
