# Generated by Django 4.2 on 2023-04-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commit', '0004_alter_commit_like_commit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='like_commit',
        ),
        migrations.AddField(
            model_name='commit',
            name='like_commit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
